In [18]:
import pandas as pd

In [19]:
df = pd.read_csv("HousingData.csv")
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2

In [20]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,486.000000,486.000000,486.000000,486.000000,506.000000,506.000000,486.000000,506.000000,506.000000,506.000000,506.000000,506.000000,486.000000,506.000000
mean,3.611874,11.211934,11.083992,0.069959,0.554695,6.284634,68.518519,3.795043,9.549407,408.237154,18.455534,356.674032,12.715432,22.532806
std,8.720192,23.388876,6.835896,0.255340,0.115878,0.702617,27.999513,2.105710,8.707259,168.537116,2.164946,91.294864,7.155871,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.081900,0.000000,5.190000,0.000000,0.449000,5.885500,45.175000,2.100175,4.000000,279.000000,17.400000,375.377500,7.125000,17.025000
50%,0.253715,0.000000,9.690000,0.000000,0.538000,6.208500,76.800000,3.207450,5.000000,330.000000,19.050000,391.440000,11.430000,21.200000
75%,3.560263,12.500000,18.100000,0.000000,0.624000,6.623500,93.975000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [21]:
df.isna().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [22]:
for column in df.columns:
    mean_value = df[column].mean()
    df[column].fillna(mean_value, inplace = True)

df.isna().sum()

C:\Users\Rohit\AppData\Local\Temp\ipykernel_34052\688729791.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(mean_value, inplace = True)

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [23]:
X = df.drop("MEDV", axis = 1)

y = df["MEDV"]

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(128, input_shape = (13,), activation = 'relu', name = 'Dense_1'))

model.add(Dense(64, activation = 'relu', name = 'Dense_2'))

model.add(Dense(1, activation = 'linear', name = 'Dense_output'))

model.compile(optimizer = 'adam', loss = 'mse', metrics = ['mae'])

model.summary()

C:\Users\Rohit\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Dense_1 (Dense)                 │ (None, 128)            │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Dense_2 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Dense_output (Dense)            │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,113 (39.50 KB)

 Trainable params: 10,113 (39.50 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
history = model.fit(X_train_scaled, y_train, epochs = 100, validation_split = 0.05, verbose = 1)

Epoch 1/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 602.9593 - mae: 22.6284 - val_loss: 509.2906 - val_mae: 20.9805
Epoch 2/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 535.9724 - mae: 21.0749 - val_loss: 437.9969 - val_mae: 19.3138
Epoch 3/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 451.5808 - mae: 19.0767 - val_loss: 344.4995 - val_mae: 16.8884
Epoch 4/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 342.9674 - mae: 16.2124 - val_loss: 233.1935 - val_mae: 13.4557
Epoch 5/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 218.1630 - mae: 12.4605 - val_loss: 131.6767 - val_mae: 9.1982
Epoch 6/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.5402 - mae: 8.5913 - val_loss: 77.9028 - val_mae: 6.4340
Epoch 7/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.5224 - mae: 6.5493 - val_loss: 64.6512 - val_mae: 5.4782
Epoch 8/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 52.0659 - mae: 5.6638 - val_loss: 55.6940 - val_mae: 5.1599
Epoch 9/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 37.8301 - mae: 4.7475 - val_loss: 55.1173 - val_mae: 5.1389
Epoch 10/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 31.2234 - mae: 4.2512 - val_loss: 55.7281 - val_mae: 5.2823
Epoch 11/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 27.7513 - mae: 3.9574 - val_loss: 59.6578 - val_mae: 5.5084
Epoch 12/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.4680 - mae: 3.8008 - val_loss: 58.3984 - val_mae: 5.4976
Epoch 13/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 23.9096 - mae: 3.7017 - val_loss: 56.8055 - val_mae: 5.3946
Epoch 14/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22.5135 - mae: 3.5807 - val_loss: 56.5504 - val_mae: 5.3470
Epoch 15/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 21.2772 - mae: 3.4820 - val_loss: 54.6481 - val_mae: 5.2697
Epoch 16/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.3906 - mae: 3.4141 - val_loss: 52.4159 - val_mae: 5.1762
Epoch 17/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.6455 - mae: 3.3596 - val_loss: 51.5469 - val_mae: 5.0979
Epoch 18/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18.6789 - mae: 3.2436 - val_loss: 51.2703 - val_mae: 5.0392
Epoch 19/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 17.9777 - mae: 3.1693 - val_loss: 51.0512 - val_mae: 5.0206
Epoch 20/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 17.4300 - mae: 3.1276 - val_loss: 48.4266 - val_mae: 4.8890
Epoch 21/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.8024 - mae: 3.0817 - val_loss: 48.6352 - val_mae: 4.8742
Epoch 22/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.2179 - mae: 3.0118 - val_loss: 48.8988 - val_mae: 4.8800
Epoch 23/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.7926 - mae: 2.9582 - val_loss: 48.1199 - val_mae: 4.8303
Epoch 24/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.3109 - mae: 2.9018 - val_loss: 49.1135 - val_mae: 4.8354
Epoch 25/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.9235 - mae: 2.8682 - val_loss: 47.0205 - val_mae: 4.7252
Epoch 26/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.5448 - mae: 2.8485 - val_loss: 46.6445 - val_mae: 4.7010
Epoch 27/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.3049 - mae: 2.8104 - val_loss: 46.1685 - val_mae: 4.6532
Epoch 28/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.0555 - mae: 2.7905 - val_loss: 44.8401 - val_mae: 4.6196
Epoch 29/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.7472 - mae: 2.7441 - val_loss: 45.9254 - val_mae: 4.6198
Epoch 30/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.4260 - mae: 2.7124 - val_loss: 43.7537 - val_mae: 4.5058
Epoch 31/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.2857 - mae: 2.7183 - val_loss: 44.6281 - val_mae: 4.5726
Epoch 32/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.8723 - mae: 2.6673 - val_loss: 42.9510 - val_mae: 4.4573
Epoch 33/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.6881 - mae: 2.6443 - val_loss: 43.6303 - val_mae: 4.5035
Epoch 34/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.4988 - mae: 2.6294 - val_loss: 41.5826 - val_mae: 4.3708
Epoch 35/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.3322 - mae: 2.6109 - val_loss: 42.7886 - val_mae: 4.4137
Epoch 36/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.2007 - mae: 2.6014 - val_loss: 42.0171 - val_mae: 4.3814
Epoch 37/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.0284 - mae: 2.5803 - val_loss: 43.6620 - val_mae: 4.4629
Epoch 38/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.8455 - mae: 2.5408 - val_loss: 41.3516 - val_mae: 4.2924
Epoch 39/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.6779 - mae: 2.5337 - val_loss: 41.1918 - val_mae: 4.2967
Epoch 40/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.5652 - mae: 2.5315 - val_loss: 40.1688 - val_mae: 4.2509
Epoch 41/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.3793 - mae: 2.5124 - val_loss: 40.8289 - val_mae: 4.2616
Epoch 42/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.3146 - mae: 2.4992 - val_loss: 41.8434 - val_mae: 4.2896
Epoch 43/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.1406 - mae: 2.4937 - val_loss: 38.2518 - val_mae: 4.1548
Epoch 44/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.0999 - mae: 2.4844 - val_loss: 37.3689 - val_mae: 4.0714
Epoch 45/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.9428 - mae: 2.4622 - val_loss: 39.2772 - val_mae: 4.1987
Epoch 46/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.7783 - mae: 2.4513 - val_loss: 39.5191 - val_mae: 4.1816
Epoch 47/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.6637 - mae: 2.4372 - val_loss: 37.5151 - val_mae: 4.0736
Epoch 48/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.6424 - mae: 2.4375 - val_loss: 38.5178 - val_mae: 4.1000
Epoch 49/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.4194 - mae: 2.4166 - val_loss: 38.3157 - val_mae: 4.0849
Epoch 50/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.3700 - mae: 2.4126 - val_loss: 38.5571 - val_mae: 4.1146
Epoch 51/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.2640 - mae: 2.4097 - val_loss: 36.6691 - val_mae: 4.0266
Epoch 52/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.1909 - mae: 2.3879 - val_loss: 37.1803 - val_mae: 4.0084
Epoch 53/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.0990 - mae: 2.3777 - val_loss: 36.6888 - val_mae: 4.0081
Epoch 54/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 10.0229 - mae: 2.3837 - val_loss: 37.2397 - val_mae: 3.9711
Epoch 55/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.9791 - mae: 2.3658 - val_loss: 37.6174 - val_mae: 4.0057
Epoch 56/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.9218 - mae: 2.3674 - val_loss: 38.1185 - val_mae: 4.0768
Epoch 57/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.7403 - mae: 2.3476 - val_loss: 36.1445 - val_mae: 3.9264
Epoch 58/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.7138 - mae: 2.3322 - val_loss: 35.9566 - val_mae: 3.9127
Epoch 59/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.6069 - mae: 2.3191 - val_loss: 36.8667 - val_mae: 3.9959
Epoch 60/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5445 - mae: 2.3221 - val_loss: 35.7936 - val_mae: 3.9314
Epoch 61/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5900 - mae: 2.3128 - val_loss: 34.3068 - val_mae: 3.8289
Epoch 62/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.4732 - mae: 2.3229 - val_loss: 36.4047 - val_mae: 4.0123
Epoch 63/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5002 - mae: 2.3186 - val_loss: 36.3625 - val_mae: 3.9391
Epoch 64/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.2591 - mae: 2.2730 - val_loss: 33.9931 - val_mae: 3.8808
Epoch 65/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.2587 - mae: 2.3066 - val_loss: 36.4097 - val_mae: 4.0248
Epoch 66/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0843 - mae: 2.2567 - val_loss: 35.2451 - val_mae: 3.9116
Epoch 67/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9967 - mae: 2.2565 - val_loss: 34.4040 - val_mae: 3.8980
Epoch 68/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9450 - mae: 2.2503 - val_loss: 34.8113 - val_mae: 3.9352
Epoch 69/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9054 - mae: 2.2408 - val_loss: 34.9205 - val_mae: 3.9214
Epoch 70/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9099 - mae: 2.2410 - val_loss: 35.2806 - val_mae: 3.9464
Epoch 71/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7475 - mae: 2.2255 - val_loss: 32.8457 - val_mae: 3.8657
Epoch 72/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7050 - mae: 2.2197 - val_loss: 33.8872 - val_mae: 3.8640
Epoch 73/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.6224 - mae: 2.1995 - val_loss: 34.4444 - val_mae: 3.9430
Epoch 74/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7151 - mae: 2.2194 - val_loss: 35.2642 - val_mae: 3.9669
Epoch 75/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5547 - mae: 2.2153 - val_loss: 33.1078 - val_mae: 3.9145
Epoch 76/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5360 - mae: 2.1880 - val_loss: 32.5133 - val_mae: 3.7982
Epoch 77/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3706 - mae: 2.1722 - val_loss: 33.7301 - val_mae: 3.9153
Epoch 78/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4213 - mae: 2.2106 - val_loss: 34.7493 - val_mae: 3.9662
Epoch 79/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1833 - mae: 2.1485 - val_loss: 31.6305 - val_mae: 3.7746
Epoch 80/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1707 - mae: 2.1552 - val_loss: 32.4971 - val_mae: 3.8758
Epoch 81/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1843 - mae: 2.1829 - val_loss: 32.2301 - val_mae: 3.8639
Epoch 82/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0472 - mae: 2.1296 - val_loss: 31.2653 - val_mae: 3.7351
Epoch 83/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9896 - mae: 2.1214 - val_loss: 34.1293 - val_mae: 3.9279
Epoch 84/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9479 - mae: 2.1437 - val_loss: 32.8157 - val_mae: 3.8668
Epoch 85/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8631 - mae: 2.1247 - val_loss: 30.4639 - val_mae: 3.7107
Epoch 86/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8158 - mae: 2.1016 - val_loss: 31.5494 - val_mae: 3.8012
Epoch 87/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7540 - mae: 2.0953 - val_loss: 31.9654 - val_mae: 3.8777
Epoch 88/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7482 - mae: 2.0941 - val_loss: 31.1268 - val_mae: 3.7675
Epoch 89/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7030 - mae: 2.0965 - val_loss: 30.4794 - val_mae: 3.8070
Epoch 90/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7123 - mae: 2.0983 - val_loss: 31.0015 - val_mae: 3.7160
Epoch 91/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4732 - mae: 2.0654 - val_loss: 28.3614 - val_mae: 3.6881
Epoch 92/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4940 - mae: 2.0802 - val_loss: 30.4040 - val_mae: 3.7799
Epoch 93/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5023 - mae: 2.0795 - val_loss: 30.5646 - val_mae: 3.7363
Epoch 94/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3539 - mae: 2.0302 - val_loss: 29.3339 - val_mae: 3.6717
Epoch 95/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3417 - mae: 2.0546 - val_loss: 28.2611 - val_mae: 3.6617
Epoch 96/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.2757 - mae: 2.0574 - val_loss: 29.2788 - val_mae: 3.6679
Epoch 97/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.2619 - mae: 2.0223 - val_loss: 29.1344 - val_mae: 3.7093
Epoch 98/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.1045 - mae: 2.0132 - val_loss: 28.6175 - val_mae: 3.6520
Epoch 99/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.1958 - mae: 2.0550 - val_loss: 27.8048 - val_mae: 3.5459
Epoch 100/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.1598 - mae: 2.0024 - val_loss: 28.6950 - val_mae: 3.6746

In [31]:
history.history

{'loss': [602.9592895507812,
  535.9723510742188,
  451.5807800292969,
  342.9674377441406,
  218.1630401611328,
  116.54016876220703,
  70.52235412597656,
  52.065887451171875,
  37.83013153076172,
  31.22340965270996,
  27.751277923583984,
  25.467966079711914,
  23.90957260131836,
  22.513473510742188,
  21.277177810668945,
  20.39055061340332,
  19.64550018310547,
  18.67893409729004,
  17.9776668548584,
  17.42997932434082,
  16.802366256713867,
  16.217906951904297,
  15.792550086975098,
  15.310888290405273,
  14.923490524291992,
  14.544805526733398,
  14.30491828918457,
  14.055476188659668,
  13.747220039367676,
  13.425997734069824,
  13.285667419433594,
  12.872300148010254,
  12.688112258911133,
  12.49878978729248,
  12.332164764404297,
  12.200724601745605,
  12.028444290161133,
  11.845540046691895,
  11.677912712097168,
  11.565247535705566,
  11.379338264465332,
  11.31462287902832,
  11.14055347442627,
  11.099940299987793,
  10.942770004272461,
  10.77829360961914,
  10.66368293762207,
  10.642437934875488,
  10.419370651245117,
  10.37000846862793,
  10.264033317565918,
  10.190852165222168,
  10.099047660827637,
  10.022886276245117,
  9.979100227355957,
  9.921778678894043,
  9.740254402160645,
  9.713846206665039,
  9.606891632080078,
  9.544488906860352,
  9.590003967285156,
  9.473213195800781,
  9.500171661376953,
  9.259076118469238,
  9.258713722229004,
  9.084346771240234,
  8.996711730957031,
  8.944961547851562,
  8.905415534973145,
  8.909917831420898,
  8.74748420715332,
  8.704994201660156,
  8.622392654418945,
  8.715052604675293,
  8.554742813110352,
  8.535970687866211,
  8.37059211730957,
  8.4213285446167,
  8.183293342590332,
  8.170720100402832,
  8.184271812438965,
  8.047229766845703,
  7.989631175994873,
  7.9479146003723145,
  7.8630757331848145,
  7.81583309173584,
  7.754036903381348,
  7.748246669769287,
  7.702950477600098,
  7.712343692779541,
  7.473226070404053,
  7.494044780731201,
  7.502339839935303,
  7.353937149047852,
  7.341732978820801,
  7.275698661804199,
  7.261934757232666,
  7.104498863220215,
  7.195751190185547,
  7.159838676452637],
 'mae': [22.628414154052734,
  21.074874877929688,
  19.076732635498047,
  16.21236801147461,
  12.460469245910645,
  8.591349601745605,
  6.549283027648926,
  5.663760185241699,
  4.7474541664123535,
  4.251203536987305,
  3.9574084281921387,
  3.8007755279541016,
  3.7017393112182617,
  3.5806827545166016,
  3.4819717407226562,
  3.414149284362793,
  3.3596324920654297,
  3.2435898780822754,
  3.169321060180664,
  3.127551555633545,
  3.0816853046417236,
  3.0118489265441895,
  2.9581515789031982,
  2.9018330574035645,
  2.8681869506835938,
  2.848539352416992,
  2.810358762741089,
  2.7904858589172363,
  2.7440743446350098,
  2.7124264240264893,
  2.7183287143707275,
  2.667315721511841,
  2.6442525386810303,
  2.6294021606445312,
  2.6109488010406494,
  2.6013689041137695,
  2.58031964302063,
  2.5407800674438477,
  2.5336921215057373,
  2.5315425395965576,
  2.512395143508911,
  2.4991512298583984,
  2.4936563968658447,
  2.4844119548797607,
  2.4621505737304688,
  2.451319456100464,
  2.437239408493042,
  2.4374747276306152,
  2.4166316986083984,
  2.4125711917877197,
  2.4097273349761963,
  2.387918472290039,
  2.377664804458618,
  2.3836638927459717,
  2.365750551223755,
  2.3674185276031494,
  2.347569704055786,
  2.332231044769287,
  2.319106101989746,
  2.3220906257629395,
  2.3128163814544678,
  2.3229339122772217,
  2.3186049461364746,
  2.272998332977295,
  2.3065617084503174,
  2.256697654724121,
  2.2565340995788574,
  2.250326633453369,
  2.240811347961426,
  2.240950107574463,
  2.2254998683929443,
  2.219712018966675,
  2.199474334716797,
  2.2194106578826904,
  2.215264320373535,
  2.1880252361297607,
  2.172166347503662,
  2.2106337547302246,
  2.1484928131103516,
  2.155238151550293,
  2.1828532218933105,
  2.1296260356903076,
  2.1213934421539307,
  2.143691062927246,
  2.124661684036255,
  2.1016101837158203,
  2.095275402069092,
  2.09409499168396,
  2.096491575241089,
  2.0982539653778076,
  2.065422773361206,
  2.0802228450775146,
  2.0794525146484375,
  2.0301642417907715,
  2.054551362991333,
  2.0574138164520264,
  2.0223352909088135,
  2.0132110118865967,
  2.054960012435913,
  2.0024161338806152],
 'val_loss': [509.2906494140625,
  437.9969177246094,
  344.4994812011719,
  233.1935272216797,
  131.6767120361328,
  77.90276336669922,
  64.65115356445312,
  55.69395446777344,
  55.11725616455078,
  55.728126525878906,
  59.65776062011719,
  58.39836120605469,
  56.80548095703125,
  56.55039978027344,
  54.648067474365234,
  52.4158821105957,
  51.54692459106445,
  51.270267486572266,
  51.051212310791016,
  48.426578521728516,
  48.63515090942383,
  48.898841857910156,
  48.11989974975586,
  49.113487243652344,
  47.02053451538086,
  46.64454650878906,
  46.168487548828125,
  44.84009552001953,
  45.92542266845703,
  43.753658294677734,
  44.62805938720703,
  42.95098876953125,
  43.63030242919922,
  41.58262634277344,
  42.78862380981445,
  42.01713180541992,
  43.6619987487793,
  41.35163497924805,
  41.191837310791016,
  40.168766021728516,
  40.828880310058594,
  41.84340286254883,
  38.251808166503906,
  37.36891555786133,
  39.27717590332031,
  39.51906204223633,
  37.51514434814453,
  38.51780700683594,
  38.3156623840332,
  38.557106018066406,
  36.66911697387695,
  37.18025207519531,
  36.68883514404297,
  37.23966979980469,
  37.61735153198242,
  38.11854553222656,
  36.14445877075195,
  35.95658874511719,
  36.86666488647461,
  35.79362106323242,
  34.30683517456055,
  36.4046630859375,
  36.36245346069336,
  33.99308776855469,
  36.40969467163086,
  35.24509811401367,
  34.40397644042969,
  34.81134796142578,
  34.92045974731445,
  35.28058624267578,
  32.84574890136719,
  33.887229919433594,
  34.444366455078125,
  35.26417541503906,
  33.107826232910156,
  32.5133056640625,
  33.73012924194336,
  34.749263763427734,
  31.630510330200195,
  32.49708938598633,
  32.23013687133789,
  31.26534652709961,
  34.12931442260742,
  32.81568145751953,
  30.46388816833496,
  31.54940414428711,
  31.965415954589844,
  31.12679672241211,
  30.47937774658203,
  31.00150489807129,
  28.361433029174805,
  30.40401268005371,
  30.56456184387207,
  29.33388328552246,
  28.261125564575195,
  29.278770446777344,
  29.134361267089844,
  28.61750030517578,
  27.804821014404297,
  28.69503402709961],
 'val_mae': [20.980457305908203,
  19.313804626464844,
  16.888368606567383,
  13.455721855163574,
  9.198165893554688,
  6.433965682983398,
  5.478237628936768,
  5.159869194030762,
  5.138876438140869,
  5.28226900100708,
  5.508370399475098,
  5.497577667236328,
  5.394647121429443,
  5.3469557762146,
  5.269680976867676,
  5.176228046417236,
  5.097858905792236,
  5.039158344268799,
  5.020637512207031,
  4.888963222503662,
  4.874208450317383,
  4.879960536956787,
  4.830333232879639,
  4.835441589355469,
  4.725164890289307,
  4.700990676879883,
  4.65324592590332,
  4.619617462158203,
  4.619775772094727,
  4.505847930908203,
  4.572611331939697,
  4.457326412200928,
  4.503525733947754,
  4.370810508728027,
  4.413679599761963,
  4.381368637084961,
  4.462924957275391,
  4.292414665222168,
  4.296704292297363,
  4.250850677490234,
  4.261580467224121,
  4.289586067199707,
  4.154767036437988,
  4.071411609649658,
  4.198672771453857,
  4.181591510772705,
  4.073648452758789,
  4.100030899047852,
  4.084939002990723,
  4.114566802978516,
  4.0266289710998535,
  4.008403301239014,
  4.008119106292725,
  3.971102714538574,
  4.005668640136719,
  4.0768280029296875,
  3.926365375518799,
  3.9127485752105713,
  3.995948314666748,
  3.931363821029663,
  3.8289425373077393,
  4.012346267700195,
  3.9390945434570312,
  3.8807575702667236,
  4.024800777435303,
  3.911621570587158,
  3.8979601860046387,
  3.9352433681488037,
  3.92138671875,
  3.9463539123535156,
  3.865687370300293,
  3.8640174865722656,
  3.9430432319641113,
  3.966902732849121,
  3.9144608974456787,
  3.7982242107391357,
  3.9152510166168213,
  3.966233253479004,
  3.77463436126709,
  3.875776529312134,
  3.8638763427734375,
  3.735053539276123,
  3.9278576374053955,
  3.8667657375335693,
  3.7107021808624268,
  3.8012356758117676,
  3.8776724338531494,
  3.7674853801727295,
  3.80704927444458,
  3.7160444259643555,
  3.688141345977783,
  3.779853343963623,
  3.73634934425354,
  3.671668529510498,
  3.661738157272339,
  3.6678881645202637,
  3.709282875061035,
  3.6520462036132812,
  3.5458970069885254,
  3.6746225357055664]}

In [32]:
mse, mae = model.evaluate(X_test_scaled, y_test)

print("mse : ", mse)
print("mae : ", mae)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.7299 - mae: 2.8071
mse :  14.729877471923828
mae :  2.8071064949035645